1 html
183Natasha/dz_html pull request #1
Opened 2024-06-01 06:25 UTC by 183Natasha

2024-06-02 14:48 UTC, GitEsense requested changes
Ознакомьтесь с комментариями, если будет необходимость - повторите пройденный материал и если что-то не понятно - задавайте вопросы

Так же дополнительно можете почитать про метатеги и заглядывайте в офф. документацию для более "широкого" ознакомления со свойствами

2024-06-02 14:48 UTC, GitEsense commented on 1-blog/index.html
> +    </header>
Тут хорошо бы все "li" сделать ещё и ссылками, т.к. у нас всё-таки навигация, а ссылка будет переходом
А вот "В" и "Мой блог" - это одно и то же, т.е. логотип + текст - одна ссылка, мы её можем вынести за nav, т.к. header у нас состоит из 3х частей
1. ссылка-логотип
2. навигационное меню (список ссылок навигации)
3. форма поиска

и получим что-то вроде
```html
<header>
   <a href="#"><span class="logo">В</span>Мой блог</a>
   <nav>
      <ul>
          <li><a href="#">Текст</a></li>
          <li><a href="#">Текст</a></li>
          <li><a href="#">Текст</a></li>
      </ul>
   </nav>
   <form action="/" method="GET">
       <label for="query"><img src="./search_icon.svg"></img></label>
       <input type="query" id="query" name="query" placeholder="Поиск...">
   </form>
</header>
```

2024-06-02 14:48 UTC, GitEsense commented on 1-blog/index.html
> +        </span>
Вот тут так же не верно
span - это строчный элемент, по сути используется для выделения текста
p - блочный текстовый элемент
h1-h6 - это заголовок (семантический блочный элемент со своей иерархией), т.е. абсолютно всегда идёт сначала h1, если есть ещё заголовок, то уже h2 (второго уровня) и т.п., заголовок h1 абсолютно всегда только один раз встречается, h2-h6 могут повторяться

Тут верно было бы использовать параграф, т.к. это "блок текстового контента", но и можно было бы внутри выделить дату как отдельный тег `datetime`
```html
<p><span class="toUpperCase">frontend</span>&bull;<datetime>12 мая 2024</datetime></p>
```

2024-06-02 14:48 UTC, GitEsense commented on 1-blog/index.html
> +    </span>
А вот тут просто h1 без спан и прочего - будет самое идеальное, ведь это действительно по контексту заголовок

2024-06-02 14:48 UTC, GitEsense commented on 1-blog/index.html
> +        <h6 class="prof">Разработчик</h6>
А это так же уже параграфы, а не заголовки

2024-06-02 14:48 UTC, GitEsense commented on 2-Form/index.html
> +    <h2>Уже есть аккаунт? <a href="#">Войти</a></h2>
Это можно оформить как h1 + p
```html
    <h1>Регистрация</h1>
    <p>Уже есть аккаунт? <a href="#">Войти</a></p>
```

2024-06-02 14:48 UTC, GitEsense commented on 2-Form/index.html
> +    <h3>Мой компания</h3>
Это так же инпут, как и "Имя" и т.п., просто показан, что идёт "ввод", когда будем стилизовать - будет 3 состояния
1. placeholder
2. focus
3. обычное

2024-06-02 14:48 UTC, GitEsense commented on 2-Form/index.html
> +        </div>
div у нас используется для объединения контента, если у нас один тег внутри - ни к чему, но такое выделение имеет право на жизнь, т.к. хорошо бы указывать и лейбл (пусть и пустой)
А имя и фамилия - как раз таки объединены - если посмотрим, то стоят рядом "в одном блоке", значит при стилизации это учтём

2024-06-02 14:48 UTC, GitEsense commented on 2-Form/index.html
> +    <form action="#">
Вообще заголовок и инпут относятся к форме, поэтому лучше вложить их сразу "внутрь" формы

2024-06-03 17:41 UTC, 183Natasha commented
Здравствуйте. 
Исправила, как Вы советовали. Единственное, немного запуталась с label в 2-Forms. Подскажите, пожалуйста, как следовало его оформить

2024-06-04 14:59 UTC, GitEsense approved these changes
Ну теперь всё отлично (есть некоторые моменты на тему лейбл в форме, предлагаю Вам их вообще убрать, Вам так легче будет стилизовать, а можете наоборот везде добавить, тогда сделаем "обёртки" для них, но это уже ближе к флексбокс доведём до ума, как раз у Вас будет практика по формам

2024-06-05 16:51 UTC, merged